export enum InjectionErrorCode {
  TOKEN_INVALID = 'TOKEN_INVALID',
  TOKEN_ALREADY_REGISTERED = 'TOKEN_ALREADY_REGISTERED',
  TOKEN_NOT_REGISTERED = 'TOKEN_NOT_REGISTERED',

  CREATION_METHOD_MISSING = 'CREATION_METHOD_MISSING',
  CREATION_MULTIPLE_METHOD = 'CREATION_MULTIPLE_METHOD',
  CREATION_METHOD_USE_CLASS_INVALID = 'CREATION_METHOD_USE_CLASS_INVALID',
  CREATION_METHOD_USE_FACTORY_INVALID = 'CREATION_METHOD_USE_FACTORY_INVALID',

  CLASS_CONSTRUCTOR_INVALID = 'CLASS_CONSTRUCTOR_INVALID',
}
