export enum InjectionErrorCode {
  REGISTER_TOKEN_MISSING = 'REGISTER_TOKEN_MISSING',
  REGISTER_TOKEN_ALREADY_REGISTERED = 'REGISTER_TOKEN_ALREADY_REGISTERED',

  REGISTER_CREATION_MISSING = 'REGISTER_CREATION_MISSING',
  REGISTER_CREATION_MULTIPLE = 'REGISTER_CREATION_MULTIPLE',

  REGISTER_USE_CLASS_INVALID = 'REGISTER_USE_CLASS_INVALID',
  REGISTER_USE_FACTORY_INVALID = 'REGISTER_USE_FACTORY_INVALID',

  RESOLVE_NOT_REGISTERED = 'RESOLVE_NOT_REGISTERED',
  RESOLVE_EXPECTED_CLASS = 'RESOLVE_EXPECTED_CLASS',
}
